### ISSUE TITLE
gradle

### ISSUE THREAD

**Issue by jjhesk** [adhamenaya/AndroidMosaicLayout#2]
what is the gradle setup for this?

**Comment by galibimtiaz** [comment]
Need gradle

**Comment by adhamenaya** [comment]
@jjhesk @galibimtiaz  It will be available soon. Thanks.

**Comment by kibotu** [comment]
https://jitpack.io/#adhamenaya/AndroidMosaicLayout/

try

compile 'com.github.adhamenaya:AndroidMosaicLayout:ea7387abd7'
