### ISSUE TITLE
Please Use NestedScrollView instade of ScrollView.

### ISSUE THREAD

**Issue by galibimtiaz** [adhamenaya/AndroidMosaicLayout#3]
ScrollView dose not respond to the collapsing toolbar layout so it would be nice if use NestedScrollView instead of ScrollView.

**Comment by adhamenaya** [comment]
@galibimtiaz please check the android studio version for the library

**Comment by adhamenaya** [comment]
@galibimtiaz did you check the updates ?

**Comment by galibimtiaz** [comment]
@adhamenaya no I haven't I am still using your old version project and using the jar file in my android studio , I could not set up this library in android studio properly , please provide a proper gradle setup so that anyone can easily include this library without sweating it will be really helpful.

**Comment by adhamenaya** [comment]
@galibimtiaz Great. I will do it soon. BTW do you have any other issues ?

**Comment by galibimtiaz** [comment]
@adhamenaya Last time I tried some low res landscape photos , but the problem was center crop wan't doing a good job , there was a white line under every big blocks and vertical blocks. I meant the photo wasn't crop in the center so the bottom was blank white , it work just fine with with high res photos though.
