### ISSUE TITLE
View recycling

### ISSUE THREAD

**Issue by squeeish** [adhamenaya/AndroidMosaicLayout#5]
Hi,

This is a great library, easy to use and it works. Could you explain if view recycling is implemented here, or is it not possible to implement?

**Comment by squeeish** [comment]
Nevermind, I tried it out and we can implement the usual ViewHolder pattern. Thanks!

**Comment by adhamenaya** [comment]
@squeeish would you mind sharing an example of using viewholder with us?

**Comment by squeeish** [comment]
It's the same common ViewHolder pattern you see for the good old ListView!

**Comment by adhamenaya** [comment]
@squeeish I know. Thank you :)
